name: 'Release: Scheduled'

permissions: {}

on:
  schedule:
    - cron: '0 0 * * 3' # Every Wednesday at 00:00 AM UTC on the default branch
  workflow_dispatch:

jobs:
  release-schedule:
    name: 'Release: Scheduled'
    uses: dargmuesli/github-actions/.github/workflows/release-schedule.yml@661e39fe1c9e484d94c6a5a9d4c9946d57c41771 # 5.1.0
    permissions:
      contents: read
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    with:
      IS_DEBOUNCED: ${{ github.event_name != 'workflow_dispatch' }}
