name: 'Release: Scheduled'

permissions: {}

on:
  schedule:
    - cron: '0 0 * * 3' # Every Wednesday at 00:00 AM UTC on the default branch
  workflow_dispatch:

jobs:
  release-schedule:
    name: 'Release: Scheduled'
    uses: dargmuesli/github-actions/.github/workflows/release-schedule.yml@d8fbc998656a0a3476bfdb091c216c3cf78cdc94 # 5.1.1
    permissions:
      contents: read
    secrets:
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
    with:
      GH_APP_ID: ${{ vars.GH_APP_ID }}
      IS_DEBOUNCED: ${{ github.event_name != 'workflow_dispatch' }}
